#!/bin/bash

JARS="../build/elephant-bird-${ELEPHANT_BIRD_VERSION}.jar"
for f in $(/bin/ls ../build/lib/test/*.jar); do
  JARS=${JARS}:$f
done

/usr/bin/java -cp ${JARS} \
  com.twitter.elephantbird.proto.HadoopProtoCodeGenerator \
  config-twadoop.yml -
