/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.twitter.elephantbird.examples.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PhoneType implements TEnum {
  MOBILE(0),
  HOME(1),
  WORK(2);

  private final int value;

  private PhoneType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PhoneType findByValue(int value) { 
    switch (value) {
      case 0:
        return MOBILE;
      case 1:
        return HOME;
      case 2:
        return WORK;
      default:
        return null;
    }
  }
}
